# Generated by Django 5.0.1 on 2024-02-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', verbose_name='File name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='File upload date')),
                ('processed', models.BooleanField(default=False, verbose_name='File processed')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
